import '../public/images/alien_planet.png'
import '../public/images/moon_settlement.jpg'
import '../public/images/mars_settlement.jpg'
import '../public/images/frankfurt.jpg'
import '../public/videos/earth_rotation.mp4'
import '../public/images/airport.png'
import '../public/images/snowboard_astro.jpg'
import '../public/images/green_future_city.jpg'
import '../public/images/planets.png'

import '../public/fonts/Aldrich-Regular.ttf'
import '../public/fonts/D-DIN-Bold.ttf'
import '../public/fonts/D-DIN.ttf'

import './components/exo-cursor.js'
import './components/exo-launch-item.js'
import './components/exo-btn.js'
import './components/exo-nav.js'
import './lib/flights.js'

import './styles/flights.css'
import './styles/globals.css'
import './styles/buttons.css'
import './styles/home.css'
import './styles/journey.css'
import './styles/nav.css'

